version: '2'
services:
    beercounterapplication-app:
        image: beercounterapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://beercounterapplication-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=beerCounterApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    beercounterapplication-mongodb:
        extends:
            file: mongodb.yml
            service: beercounterapplication-mongodb
